{
  "openapi": "3.0.1",
  "info": {
    "title": "SberDisk Subscription Api",
    "version": "v1"
  },
  "paths": {
    "/api/admin/tariff-group": {
      "post": {
        "tags": [
          "Admin"
        ],
        "summary": "Добавление группы тарифов",
        "requestBody": {
          "description": "",
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/TariffGroup"
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TariffGroup"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/TariffGroup"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/TariffGroup"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "get": {
        "tags": [
          "Admin"
        ],
        "summary": "Получение списка групп тарифов",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/TariffGroup"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Admin"
        ],
        "summary": "Обновление группы тарифов",
        "requestBody": {
          "description": "",
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/TariffGroup"
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TariffGroup"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/TariffGroup"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/TariffGroup"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/admin/tariff-group/{id}": {
      "delete": {
        "tags": [
          "Admin"
        ],
        "summary": "Удаление группы тарифов",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/admin/tariff": {
      "get": {
        "tags": [
          "Admin"
        ],
        "summary": "Получение списка тарифов",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Tariff"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Admin"
        ],
        "summary": "Добавление тарифа",
        "requestBody": {
          "description": "",
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/Tariff"
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Tariff"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Tariff"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/Tariff"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "put": {
        "tags": [
          "Admin"
        ],
        "summary": "Обновление тарифа",
        "requestBody": {
          "description": "",
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/Tariff"
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Tariff"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Tariff"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/Tariff"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/admin/tariff/{id}": {
      "delete": {
        "tags": [
          "Admin"
        ],
        "summary": "Удаление тарифа",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/admin/subscription": {
      "get": {
        "tags": [
          "Admin"
        ],
        "summary": "Получение списка подписок пользователей",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Subscription"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Admin"
        ],
        "summary": "Добавление новой подписки",
        "requestBody": {
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/Subscription"
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Subscription"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Subscription"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/Subscription"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Subscription"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Admin"
        ],
        "summary": "Обновление подписки пользователя",
        "requestBody": {
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/Subscription"
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Subscription"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Subscription"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/Subscription"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Subscription"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/admin/client/{id}": {
      "get": {
        "tags": [
          "Admin"
        ],
        "summary": "Возвращает пользователя по id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Идентификатор пользователя Guid",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "username",
            "in": "query",
            "description": "Идентификатор пользователя в NC",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Client"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/admin/client": {
      "get": {
        "tags": [
          "Admin"
        ],
        "summary": "Возвращает список пользователей",
        "parameters": [
          {
            "name": "username",
            "in": "query",
            "description": "Идентификатор пользователя в NC",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Client"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/Notification/appstore": {
      "get": {
        "tags": [
          "Notification"
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "post": {
        "tags": [
          "Notification"
        ],
        "requestBody": {
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/AppleNotificationRequest"
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AppleNotificationRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/AppleNotificationRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/AppleNotificationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/Notification/appstore/transaction": {
      "post": {
        "tags": [
          "Notification"
        ],
        "requestBody": {
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/AppleTransactionRequest"
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AppleTransactionRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/AppleTransactionRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/AppleTransactionRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/Notification/google/transaction": {
      "post": {
        "tags": [
          "Notification"
        ],
        "requestBody": {
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/GoogleTransactionRequest"
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/GoogleTransactionRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/GoogleTransactionRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/GoogleTransactionRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/Notification/google": {
      "post": {
        "tags": [
          "Notification"
        ],
        "requestBody": {
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/GoogleNotificationRequest"
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/GoogleNotificationRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/GoogleNotificationRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/GoogleNotificationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/products": {
      "get": {
        "tags": [
          "SberDiskSubscription"
        ],
        "summary": "Возвращает список доступных тарифов",
        "parameters": [
          {
            "name": "clientId",
            "in": "query",
            "description": "Идентификатор пользователя (uid) во внешней системе",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "billingType",
            "in": "query",
            "description": "Фильтр по типу биллинговой платформы 1 - Ecom, 2 - Google, 3 - Apple, 0 - все\r\n            если параметр не указан - используется 1 - Ecom\r\n            чтобы получить все записи необходимо указать 0",
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 1
            }
          },
          {
            "name": "groupType",
            "in": "query",
            "description": "Фильтр по типу группы 1 - по квоте, 2 - по тарифу, 0 - все\r\n            если параметр не указан - используется 1 - по квоте\r\n            чтобы получить все записи необходимо указать 0",
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetProductsResponse"
                },
                "example": {
  "tariffs": [
    {
      "name": "+100 ГБ",
      "products": [
        {
          "id": 1,
          "monthlyPrice": "99",
          "pricingType": 1,
          "isActivated": false
        },
        {
          "id": 1,
          "monthlyPrice": "83",
          "pricingType": 2,
          "isActivated": false
        }
      ],
      "isActivated": true
    },
    {
      "name": "+1 ТБ",
      "products": [
        {
          "id": 3,
          "monthlyPrice": "300",
          "pricingType": 1,
          "isActivated": false
        },
        {
          "id": 4,
          "monthlyPrice": "249",
          "pricingType": 2,
          "isActivated": false
        }
      ],
      "isActivated": false
    }
  ]
}
              }
            }
          }
        }
      }
    },
    "/order/register": {
      "post": {
        "tags": [
          "SberDiskSubscription"
        ],
        "summary": "Регистрирует заказ в E-Com Сбербанка",
        "requestBody": {
          "description": "",
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterPurchaseRequest"
              },
              "example": {
  "clientId": "spashorin@altatec.ru",
  "productId": 1,
  "successUrl": "https://files.sberdisk.ru/purchase/success",
  "failUrl": "https://files.sberdisk.ru/purchase/success",
  "withAutoRenew": false
}
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterPurchaseRequest"
              },
              "example": {
  "clientId": "spashorin@altatec.ru",
  "productId": 1,
  "successUrl": "https://files.sberdisk.ru/purchase/success",
  "failUrl": "https://files.sberdisk.ru/purchase/success",
  "withAutoRenew": false
}
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterPurchaseRequest"
              },
              "example": {
  "clientId": "spashorin@altatec.ru",
  "productId": 1,
  "successUrl": "https://files.sberdisk.ru/purchase/success",
  "failUrl": "https://files.sberdisk.ru/purchase/success",
  "withAutoRenew": false
}
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterPurchaseRequest"
              },
              "example": {
  "clientId": "spashorin@altatec.ru",
  "productId": 1,
  "successUrl": "https://files.sberdisk.ru/purchase/success",
  "failUrl": "https://files.sberdisk.ru/purchase/success",
  "withAutoRenew": false
}
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegisterPurchaseResponse"
                },
                "example": {
  "resultCode": 0,
  "resultMessage": null,
  "redirectUrl": "https://securepayments.sberbank.ru/payment/merchants/sbersafe/payment_ru.html?mdOrder=adf733e1-9b74-7cb2-b458-b13201d9aa71"
}
              }
            }
          }
        }
      }
    },
    "/order/confirm": {
      "post": {
        "tags": [
          "SberDiskSubscription"
        ],
        "summary": "Проверяет статус заказа и выделяет квоту, если заказ оплачен",
        "requestBody": {
          "description": "",
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/ConfirmPurchaseRequest"
              },
              "example": {
  "correlationId": null,
  "orderId": "adf733e1-9b74-7cb2-b458-b13201d9aa71",
  "clientId": "spashorin@altatec.ru"
}
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ConfirmPurchaseRequest"
              },
              "example": {
  "correlationId": null,
  "orderId": "adf733e1-9b74-7cb2-b458-b13201d9aa71",
  "clientId": "spashorin@altatec.ru"
}
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/ConfirmPurchaseRequest"
              },
              "example": {
  "correlationId": null,
  "orderId": "adf733e1-9b74-7cb2-b458-b13201d9aa71",
  "clientId": "spashorin@altatec.ru"
}
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/ConfirmPurchaseRequest"
              },
              "example": {
  "correlationId": null,
  "orderId": "adf733e1-9b74-7cb2-b458-b13201d9aa71",
  "clientId": "spashorin@altatec.ru"
}
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ConfirmPurchaseResponse"
                },
                "example": {
  "resultCode": 0,
  "resultMessage": "Успешно",
  "status": 3
}
              }
            }
          }
        }
      }
    },
    "/subscriptions": {
      "get": {
        "tags": [
          "SberDiskSubscription"
        ],
        "summary": "Возвращает список активных подписок пользователя",
        "parameters": [
          {
            "name": "userId",
            "in": "query",
            "description": "Идентификатор пользователя",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetSubscriptionsResponse"
                }
              }
            }
          }
        }
      }
    },
    "/subscriptions/history": {
      "get": {
        "tags": [
          "SberDiskSubscription"
        ],
        "summary": "Возвращает историю подписок пользователя",
        "parameters": [
          {
            "name": "userId",
            "in": "query",
            "description": "Идентификатор пользователя",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetSubscriptionsResponse"
                }
              }
            }
          }
        }
      }
    },
    "/subscriptions/update/{subscriptionId}": {
      "put": {
        "tags": [
          "SberDiskSubscription"
        ],
        "summary": "Включает/отключает автопродление подписки пользователя",
        "parameters": [
          {
            "name": "userId",
            "in": "query",
            "description": "Идентификатор пользователя",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "subscriptionId",
            "in": "path",
            "description": "Идентификатор подписки",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "name": "autoRenew",
            "in": "query",
            "schema": {
              "type": "boolean"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ClientSubscription"
                }
              }
            }
          }
        }
      }
    },
    "/actualizeQuota": {
      "get": {
        "tags": [
          "SberDiskSubscription"
        ],
        "parameters": [
          {
            "name": "username",
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "TariffGroup": {
        "type": "object",
        "properties": {
          "Id": {
            "type": "integer",
            "description": "Идентификатор",
            "format": "int32"
          },
          "Type": {
            "type": "integer",
            "description": "1 - по величине квоты\r\n2 - по тарифу",
            "format": "int32"
          },
          "Name": {
            "type": "string",
            "description": "Наименование",
            "nullable": true
          },
          "Description": {
            "type": "string",
            "description": "Описание",
            "nullable": true
          },
          "Enabled": {
            "type": "boolean",
            "description": "Активность"
          },
          "CreateDate": {
            "type": "string",
            "description": "Дата создания",
            "format": "date-time"
          },
          "ChangeDate": {
            "type": "string",
            "description": "Дата изменения",
            "format": "date-time"
          }
        },
        "additionalProperties": false,
        "description": "группа тарифов, с определённой квотой"
      },
      "Tariff": {
        "type": "object",
        "properties": {
          "Id": {
            "type": "integer",
            "description": "Идентификатор тарифа",
            "format": "int32"
          },
          "Name": {
            "type": "string",
            "description": "Название тарифа",
            "nullable": true
          },
          "Description": {
            "type": "string",
            "description": "Описание тарифа",
            "nullable": true
          },
          "Type": {
            "type": "integer",
            "description": "1 - базовый\r\n2 - промо\r\n3 - подписка",
            "format": "int32"
          },
          "ValidFrom": {
            "type": "string",
            "description": "Дата начала действия",
            "format": "date-time",
            "nullable": true
          },
          "ValidTo": {
            "type": "string",
            "description": "Дата окончания действия",
            "format": "date-time",
            "nullable": true
          },
          "Status": {
            "type": "integer",
            "description": "1 - автивен\r\n2 - заблокирован",
            "format": "int32"
          },
          "BillingType": {
            "type": "integer",
            "description": "1 - Ecom\r\n2 - Google\r\n3 - Apple",
            "format": "int32"
          },
          "BillingTariffId": {
            "type": "string",
            "description": "идентификатор тарифа во внешней системе",
            "nullable": true
          },
          "Price": {
            "type": "integer",
            "description": "Стоимость в копейках",
            "format": "int32"
          },
          "PeriodType": {
            "type": "integer",
            "description": "тип периода действия\r\n1 - день\r\n2 - месяц\r\n3 - год",
            "format": "int32"
          },
          "PeriodValue": {
            "type": "integer",
            "description": "значение периода действия",
            "format": "int32"
          },
          "GracePeriodType": {
            "type": "integer",
            "description": "тип льготного периода по окончании действия подписки\r\n1 - день\r\n2 - месяц\r\n3 - год",
            "format": "int32"
          },
          "GracePeriodValue": {
            "type": "integer",
            "description": "значение льготного периода по окончании действия подписки",
            "format": "int32"
          },
          "QuotaMeasure": {
            "type": "integer",
            "description": "Единицы измерения квоты\r\n1 - МБ\r\n2 - ГБ\r\n3 - ТБ",
            "format": "int32"
          },
          "QuotaValue": {
            "type": "integer",
            "description": "Значение квоты",
            "format": "int32"
          },
          "TariffGroups": {
            "type": "array",
            "items": {
              "type": "integer",
              "format": "int32"
            },
            "description": "Идентификаторы групп, в которых состоит тариф",
            "nullable": true
          },
          "CreateDate": {
            "type": "string",
            "description": "Дата создания",
            "format": "date-time"
          },
          "ChangeDate": {
            "type": "string",
            "description": "Дата изменения",
            "format": "date-time"
          }
        },
        "additionalProperties": false,
        "description": "Тариф"
      },
      "Subscription": {
        "type": "object",
        "properties": {
          "Id": {
            "type": "integer",
            "format": "int64"
          },
          "ClientId": {
            "type": "string",
            "format": "uuid"
          },
          "TariffId": {
            "type": "integer",
            "format": "int32"
          },
          "AppleSubscriptionId": {
            "type": "integer",
            "format": "int64",
            "nullable": true
          },
          "GoogleSubscriptionId": {
            "type": "integer",
            "format": "int64",
            "nullable": true
          },
          "EcomSubscriptionId": {
            "type": "integer",
            "format": "int64",
            "nullable": true
          },
          "Status": {
            "type": "integer",
            "format": "int32"
          },
          "WithAutoRenew": {
            "type": "boolean"
          },
          "ValidFrom": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "ValidTo": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "CreateDate": {
            "type": "string",
            "format": "date-time"
          },
          "ChangeDate": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      },
      "Client": {
        "type": "object",
        "properties": {
          "Id": {
            "type": "string",
            "format": "uuid"
          },
          "Username": {
            "type": "string",
            "nullable": true
          },
          "Status": {
            "type": "integer",
            "format": "int32"
          },
          "CreateDate": {
            "type": "string",
            "format": "date-time"
          },
          "ChangeDate": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      },
      "ReceiptInfo": {
        "type": "object",
        "properties": {
          "SubscriptionGroupId": {
            "type": "string",
            "nullable": true
          },
          "UniqueVendorIdentifier": {
            "type": "string",
            "nullable": true
          },
          "OriginalPurchaseDateMs": {
            "type": "string",
            "nullable": true
          },
          "PurchaseDateMs": {
            "type": "string",
            "nullable": true
          },
          "ItemId": {
            "type": "string",
            "nullable": true
          },
          "UniqueId": {
            "type": "string",
            "nullable": true
          },
          "OriginalTransactionId": {
            "type": "string",
            "nullable": true
          },
          "ExpireDate": {
            "type": "string",
            "nullable": true
          },
          "ExpireDateFormatted": {
            "type": "string",
            "nullable": true
          },
          "TransactionId": {
            "type": "string",
            "nullable": true
          },
          "ProductId": {
            "type": "string",
            "nullable": true
          },
          "PurchaseDate": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "AppleNotificationRequest": {
        "type": "object",
        "properties": {
          "LatestReceipt": {
            "type": "string",
            "nullable": true
          },
          "LatestReceiptInfo": {
            "allOf": [
              {
                "$ref": "#/components/schemas/ReceiptInfo"
              }
            ],
            "nullable": true
          },
          "WithAutoRenew": {
            "type": "boolean"
          },
          "ProductId": {
            "type": "string",
            "nullable": true
          },
          "NotificationType": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "AppleTransactionRequest": {
        "type": "object",
        "properties": {
          "Username": {
            "type": "string",
            "nullable": true
          },
          "TransactionId": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "GoogleTransactionRequest": {
        "type": "object",
        "properties": {
          "Username": {
            "type": "string",
            "nullable": true
          },
          "PurchaseToken": {
            "type": "string",
            "nullable": true
          },
          "PackageName": {
            "type": "string",
            "nullable": true
          },
          "SubscriptionId": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "GoogleNotificationMessage": {
        "type": "object",
        "properties": {
          "Id": {
            "type": "string",
            "nullable": true
          },
          "Data": {
            "type": "string",
            "nullable": true
          },
          "PublishDate": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      },
      "GoogleNotificationRequest": {
        "type": "object",
        "properties": {
          "Message": {
            "allOf": [
              {
                "$ref": "#/components/schemas/GoogleNotificationMessage"
              }
            ],
            "nullable": true
          },
          "Subscription": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "PricingType": {
        "enum": [
          1,
          2
        ],
        "type": "integer",
        "description": "Тип тарификации",
        "format": "int32"
      },
      "Product": {
        "type": "object",
        "properties": {
          "Id": {
            "type": "integer",
            "description": "Идентификатор тарифа",
            "format": "int32"
          },
          "MonthlyPrice": {
            "type": "string",
            "description": "Стоимость в рублях за месяц",
            "nullable": true
          },
          "PricingType": {
            "allOf": [
              {
                "$ref": "#/components/schemas/PricingType"
              }
            ],
            "description": "Тип тарификации 1 - помесячно, 2 - ежегодно"
          },
          "IsActivated": {
            "type": "boolean",
            "description": "Указывает активирован ли у пользователя хотя бы один тариф из группы с таким же типом периода тарификации"
          }
        },
        "additionalProperties": false,
        "description": "Тариф"
      },
      "ProductGroup": {
        "type": "object",
        "properties": {
          "Name": {
            "type": "string",
            "description": "Название группы",
            "nullable": true
          },
          "Products": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Product"
            },
            "description": "Список тарифов",
            "nullable": true
          },
          "IsActivated": {
            "type": "boolean",
            "description": "Указывает активирован ли у пользователя хотя бы один тариф из группы"
          }
        },
        "additionalProperties": false,
        "description": "Группа тарифов с определённой квотой"
      },
      "GetProductsResponse": {
        "type": "object",
        "properties": {
          "Tariffs": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ProductGroup"
            },
            "description": "Доступные тарифы",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "RegisterPurchaseRequest": {
        "required": [
          "ClientId",
          "SuccessUrl"
        ],
        "type": "object",
        "properties": {
          "ClientId": {
            "type": "string",
            "description": "Идентификатор клиента во внешней системе"
          },
          "ProductId": {
            "type": "integer",
            "description": "Идентификатор продукта",
            "format": "int32"
          },
          "SuccessUrl": {
            "type": "string",
            "description": "Адрес для перенаправления в случае успешной оплаты"
          },
          "FailUrl": {
            "type": "string",
            "description": "Адрес для перенаправления в случае неуспешной оплаты",
            "nullable": true
          },
          "WithAutoRenew": {
            "type": "boolean",
            "description": "С автопродлением"
          }
        },
        "additionalProperties": false,
        "description": "Запрос регистрации заказа"
      },
      "RegisterPurchaseResponse": {
        "type": "object",
        "properties": {
          "ResultCode": {
            "type": "integer",
            "description": "Код ответа\r\n0 - успех\r\n1 - неуспех",
            "format": "int32"
          },
          "ResultMessage": {
            "type": "string",
            "description": "Расшифровка ResultCode",
            "nullable": true
          },
          "RedirectUrl": {
            "type": "string",
            "description": "адрес, по которому нужно перенаправить пользователя",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": "Ответ на запрос регистрации заказа"
      },
      "ConfirmPurchaseRequest": {
        "required": [
          "OrderId"
        ],
        "type": "object",
        "properties": {
          "CorrelationId": {
            "type": "string",
            "format": "uuid",
            "nullable": true
          },
          "OrderId": {
            "type": "string",
            "description": "Идентификатор (orderId), полученный при возврате со страницы оплаты Банка",
            "format": "uuid"
          },
          "ClientId": {
            "type": "string",
            "description": "Идентификатор (uid) клиента во внешней системе",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": "Запрос подтверждения заказа"
      },
      "PurchaseStatus": {
        "enum": [
          1,
          2,
          3,
          4,
          5
        ],
        "type": "integer",
        "format": "int32"
      },
      "ConfirmPurchaseResponse": {
        "type": "object",
        "properties": {
          "ResultCode": {
            "type": "integer",
            "description": "Код ответа\r\n0 - успех\r\n1 - неуспех",
            "format": "int32"
          },
          "ResultMessage": {
            "type": "string",
            "description": "Текстовая расшифровка ответа",
            "nullable": true
          },
          "Status": {
            "allOf": [
              {
                "$ref": "#/components/schemas/PurchaseStatus"
              }
            ],
            "description": "Статус заказа\r\n1 - зарегистрирован в биллинге, не оплачен\r\n2 - зарегистрирован в E-Com, не оплачен\r\n3 - зарегистрирован, оплачен\r\n4 - зарегистрирован, оплата не удалась\r\n5 - зарегистрирован, произведен возврат средств",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": "Ответ на запрос подтверждения оплаты"
      },
      "ClientSubscription": {
        "type": "object",
        "properties": {
          "Id": {
            "type": "integer",
            "description": "Идентификатор подписки",
            "format": "int64"
          },
          "Name": {
            "type": "string",
            "description": "Название тарифа",
            "nullable": true
          },
          "TariffId": {
            "type": "integer",
            "description": "Идентификатор тарифа",
            "format": "int32"
          },
          "Status": {
            "type": "string",
            "description": "Состояние подписки",
            "nullable": true
          },
          "WithAutoRenew": {
            "type": "boolean",
            "description": "Включено ли автопродление"
          },
          "ValidTo": {
            "type": "string",
            "description": "Дата окончание действия",
            "format": "date-time",
            "nullable": true
          },
          "ValidFrom": {
            "type": "string",
            "description": "Дата начала действия",
            "format": "date-time",
            "nullable": true
          },
          "QuotaMeasure": {
            "type": "integer",
            "description": "Единица измерения квоты:\r\n1 - Мегабайт\r\n2 - Гигабайт\r\n3 - Терабайт",
            "format": "int32"
          },
          "QuotaValue": {
            "type": "integer",
            "description": "Значение квоты",
            "format": "int32"
          },
          "BillingTypeId": {
            "type": "integer",
            "description": "Тип биллинга, через который приобретена подписка\r\n1 - Ecom\r\n2 - Google\r\n3 - Apple",
            "format": "int32"
          },
          "PricingType": {
            "allOf": [
              {
                "$ref": "#/components/schemas/PricingType"
              }
            ],
            "description": "Тип тарификации 1 - помесячно, 2 - ежегодно"
          }
        },
        "additionalProperties": false,
        "description": "Подписка"
      },
      "GetSubscriptionsResponse": {
        "type": "object",
        "properties": {
          "Subscriptions": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ClientSubscription"
            },
            "description": "Активные подписки",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": "Ответ на запрос списка подписок"
      }
    }
  }
}